version: '3.7'
services:
  crypto:
    build: .
    command: python run.py
    ports:
      - "5000:5000"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
